### ISSUE TITLE
Can this library be used with the Bing API Sandbox?

### ISSUE THREAD

**Issue by rob-orch** [tmarois/laravel-ads-sdk#13]
Hello,

first off, this library looks really awesome. I've tried setting up those services individually and it is just so much work and I can't get it to work most of the time - you are really helping me so much!

Now I wanted to start developing with this library using the Bing Ads API. When developing directly with the SDK I used the sandbox environment to test all my things but I couldn't find any information on how to use the sandbox in this library.

Is is possible to use the Bing Ads Sandbox with this library? If yes, how would I do that?

Again, thank you so much for taking the time to develop this library and open-sourcing it!

**Comment by timothymarois** [comment]
@rob-orch Thanks! I'll merge your request in! That was the goal to build one SDK to run both Google/Bing since they can be more complicated to work with separately. Multiple marketing agencies use this library so far, it helps speed up development on most of these projects. Let me know if you have any more feedback. Greatly appreciated.
