### ISSUE TITLE
How to create campaign ..?

### ISSUE THREAD

**Issue by reyadek** [tmarois/laravel-ads-sdk#3]
i has install and use this library, and i have done and understand how to use, i have done to get my campaign and edit name of campaign by use this library.....but how this library **create campaign**, any idea..? @timothymarois

**Comment by timothymarois** [comment]
Hey @reyadek At the moment this API is designed to pull existing campaigns and is heavily based on pulling reporting data from most of the report apis. Always welcome for a pull request on more features. But since the Google/Bing interfaces + they both have editors, this allows easy creation of new items, it just was never a priority for us to build it within the SDK itself.

**Comment by reyadek** [comment]
Thankyou for replay @timothymarois
