### ISSUE TITLE
Redirect uri for google ads should be set from config file 

### ISSUE THREAD

**Issue by MustafaElKhalifa** [tmarois/laravel-ads-sdk#4]
You already hard coded the redirect uri while generating the refresh token and that return error response from google as **redirect_uri_mismatch**

**Comment by timothymarois** [comment]
@MustafaElKhalifa That's a good point if you want to customize it. The current redirect Uri is `urn:ietf:wg:oauth:2.0:oob` and that is because the way you're supposed to activate the refresh token only needs to use a generic string, I would check the setup again, its designed so you do not need to use a real redirect uri because you use the command line `php artisan laravelads:token:generate --service=GoogleAds` and that prints out a URL to paste in your browser, then it gives you a code to paste back into command line to retrieve your refresh token.

**Comment by timothymarois** [comment]
Hey @MustafaElKhalifa 

I released a new update regarding Bings changes and added that config variable for use. 

https://github.com/tmarois/laravel-ads-sdk/releases/tag/v1.2.13

Inside the config of `bing-ads.php` add

```php
'redirect_uri' => 'https://login.microsoftonline.com/common/oauth2/nativeclient'
```

However, by default, I have made it so that it will use that URL if a redirect uri is not found in the config. I have tested this out today and it worked.
